"""Action-oriented advanced workflows."""

from agentdebug.runtime.plugins.registry import register_action_plugin
from agentdebug.diagnose.attribute import (
    AllAtOnceAttributor,
    AttributionBudget,
    AttributionResult,
    Attributor,
    BinarySearchAttributor,
    Blame,
    CounterfactualAttributor,
    EnsembleAttributor,
    HeuristicAttributor,
    SBFLAttributor,
    StepByStepAttributor,
)
from agentdebug.hub import (
    Bundle,
    BundleManifest,
    HubBackend,
    DEFAULT_REDACTIONS,
    GitHubBackend,
    HuggingFaceBackend,
    LocalHubBackend,
    ScrubReport,
    Scrubber,
    backend_from_spec,
    build_manifest,
    pack_bundle,
    parse_spec,
    scrub_trajectory,
    unpack_bundle,
)
from agentdebug.diagnose.recover import (
    DEFAULT_VERIFIERS,
    AutoManualRules,
    CompensationSpec,
    Compensator,
    CriticRecoverer,
    DeepDebugRecovery,
    FixProposal,
    Recoverer,
    ReflexionSuggestion,
    SagaRollback,
    SelfRefineLoop,
    VerifierSpec,
)

__all__ = [
    'AllAtOnceAttributor',
    'AttributionBudget',
    'AttributionResult',
    'Attributor',
    'AutoManualRules',
    'BinarySearchAttributor',
    'Blame',
    'Bundle',
    'BundleManifest',
    'CompensationSpec',
    'Compensator',
    'CounterfactualAttributor',
    'CriticRecoverer',
    'DeepDebugRecovery',
    'DEFAULT_REDACTIONS',
    'DEFAULT_VERIFIERS',
    'EnsembleAttributor',
    'FixProposal',
    'GitHubBackend',
    'HeuristicAttributor',
    'HubBackend',
    'HuggingFaceBackend',
    'LocalHubBackend',
    'Recoverer',
    'ReflexionSuggestion',
    'SBFLAttributor',
    'SagaRollback',
    'ScrubReport',
    'Scrubber',
    'SelfRefineLoop',
    'StepByStepAttributor',
    'VerifierSpec',
    'backend_from_spec',
    'build_manifest',
    'pack_bundle',
    'parse_spec',
    'scrub_trajectory',
    'unpack_bundle',
]

register_action_plugin(
    'action.attribution',
    'Attribution Backends',
    version='1',
    capabilities=['blame_localization'],
    source_module='agentdebug.attribution',
)
register_action_plugin(
    'action.recovery',
    'Recovery Strategies',
    version='1',
    capabilities=['fix_suggestions', 'recovery_plans'],
    source_module='agentdebug.recovery',
)
register_action_plugin(
    'action.hub',
    'Error Hub',
    version='1',
    capabilities=['bundle_push', 'bundle_pull', 'bundle_list'],
    source_module='agentdebug.hub',
)
